name: test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.10'
          - '3.11-dev'
        attempt:
          - 1
          - 2
          - 3
          - 4
          - 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}

    - name: Install packages
      run: python -m pip install coverage==6.3

    - name: Coverage info
      run: coverage debug sys

    - name: Show package versions
      run: pip freeze

    - name: Run test script
      run: python test.py

    - name: Run test script with coverage
      run: coverage run test.py
